-- Migration: switch_files_id_to_uuid
--
-- Replace public.files.id from bigserial (auto-increment bigint) to a
-- UUID primary key generated by PostgreSQL. This:
--   - stops exposing sequential numeric ids in the public /files/<id>
--     access URLs (now /files/<uuid> — unguessable, better for share links)
--   - matches the new upload flow where the S3 key is also a random UUID,
--     so neither the DB id nor the storage key leaks user-supplied info
--
-- file_logs is left untouched — its file_id column is varchar(128) and
-- already stores whatever string the route passes (uuid or bigint alike).
--
-- Drop + recreate because changing a primary-key column type in place is
-- messy. The previous table only held test data from the migration phase,
-- so data loss is acceptable.

DROP TABLE IF EXISTS public.files CASCADE;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.files (
    id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    key         varchar(512) NOT NULL,
    bucket      varchar(128),
    expires_at  timestamptz  NOT NULL,
    metadata    jsonb        NOT NULL DEFAULT '{}'::jsonb,
    status      varchar(32)  NOT NULL DEFAULT 'uploaded',
    created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_files_expires_at_status ON public.files (expires_at, status);
CREATE INDEX IF NOT EXISTS idx_files_key               ON public.files (key);

ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;

-- Same RLS shape as the original migration: service_role (server API Key)
-- bypasses RLS; anon / authenticated get read-only access so the public
-- /files/<uuid> redirect works without a backend hop, but cannot write.
CREATE POLICY files_select_all ON public.files
    FOR SELECT TO anon, authenticated
    USING (true);

CREATE POLICY files_no_insert_to_anon ON public.files
    FOR INSERT TO anon, authenticated
    WITH CHECK (false);

CREATE POLICY files_no_update_to_anon ON public.files
    FOR UPDATE TO anon, authenticated
    USING (false)
    WITH CHECK (false);

CREATE POLICY files_no_delete_to_anon ON public.files
    FOR DELETE TO anon, authenticated
    USING (false);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.files TO authenticated;
-- UUID PK has no sequence, so no SEQUENCE GRANT is needed.
